ktor {
    deployment {
        port = 8080
        host = "0.0.0.0"
    }
    application {
        modules = [ dev.kbwallet.server.ApplicationKt.module ]
    }
}

jwt {
    secret = "kbwallet-jwt-secret-change-in-production-32chars!"
    issuer = "kbwallet-server"
    audience = "kbwallet-users"
    accessTokenExpirationMs = 86400000       # 24 hours
    refreshTokenExpirationMs = 604800000      # 7 days
}

password {
    iterations = 10000
    keyLength = 256
}
