package dev.kbwallet.app.theme

import androidx.compose.ui.graphics.Color

// Neon-green dark scheme (default) + green-tinted light scheme
// Based on KBWallet_UI_Design_Description.txt

// ── DARK COLOR SCHEME (neon-green on deep dark background) ──

internal val PrimaryDark = Color(0xFF00FF00)
internal val OnPrimaryDark = Color(0xFF000000)
internal val PrimaryContainerDark = Color(0xFF004400)
internal val OnPrimaryContainerDark = Color(0xFF00FF00)
internal val SecondaryDark = Color(0xFF00E600)
internal val OnSecondaryDark = Color(0xFF000000)
internal val SecondaryContainerDark = Color(0xFF003300)
internal val OnSecondaryContainerDark = Color(0xFF00E600)
internal val TertiaryDark = Color(0xFF00CC00)
internal val OnTertiaryDark = Color(0xFF000000)
internal val TertiaryContainerDark = Color(0xFF002200)
internal val OnTertiaryContainerDark = Color(0xFF00CC00)
internal val ErrorDark = Color(0xFFFFB4AB)
internal val OnErrorDark = Color(0xFF690005)
internal val ErrorContainerDark = Color(0xFF93000A)
internal val OnErrorContainerDark = Color(0xFFFFDAD6)
internal val BackgroundDark = Color(0xFF121212)
internal val OnBackgroundDark = Color(0xFFE3E3E3)
internal val SurfaceDark = Color(0xFF1A1A1A)
internal val OnSurfaceDark = Color(0xFFE3E3E3)
internal val SurfaceVariantDark = Color(0xFF2B2B2B)
internal val OnSurfaceVariantDark = Color(0xFFCAC4D0)
internal val OutlineDark = Color(0xFF4A4A4A)
internal val OutlineVariantDark = Color(0xFF49454F)
internal val ScrimDark = Color(0xFF000000)
internal val InverseSurfaceDark = Color(0xFFE6E0E9)
internal val InverseOnSurfaceDark = Color(0xFF313033)
internal val InversePrimaryDark = Color(0xFF00C800)

// Surface container hierarchy — dark
internal val SurfaceDimDark = Color(0xFF141218)
internal val SurfaceBrightDark = Color(0xFF3B383E)
internal val SurfaceContainerLowestDark = Color(0xFF0F0D13)
internal val SurfaceContainerLowDark = Color(0xFF1D1B20)
internal val SurfaceContainerDark = Color(0xFF211F26)
internal val SurfaceContainerHighDark = Color(0xFF2B2930)
internal val SurfaceContainerHighestDark = Color(0xFF36343B)

// ── LIGHT COLOR SCHEME (green on light background) ──

internal val PrimaryLight = Color(0xFF006E00)
internal val OnPrimaryLight = Color(0xFFFFFFFF)
internal val PrimaryContainerLight = Color(0xFF00FF00)
internal val OnPrimaryContainerLight = Color(0xFF002200)
internal val SecondaryLight = Color(0xFF006600)
internal val OnSecondaryLight = Color(0xFFFFFFFF)
internal val SecondaryContainerLight = Color(0xFF00E600)
internal val OnSecondaryContainerLight = Color(0xFF001A00)
internal val TertiaryLight = Color(0xFF005000)
internal val OnTertiaryLight = Color(0xFFFFFFFF)
internal val TertiaryContainerLight = Color(0xFF00CC00)
internal val OnTertiaryContainerLight = Color(0xFF001400)
internal val ErrorLight = Color(0xFFBA1A1A)
internal val OnErrorLight = Color(0xFFFFFFFF)
internal val ErrorContainerLight = Color(0xFFFFDAD6)
internal val OnErrorContainerLight = Color(0xFF410002)
internal val BackgroundLight = Color(0xFFFDF8F6)
internal val OnBackgroundLight = Color(0xFF1C1B1F)
internal val SurfaceLight = Color(0xFFFDF8F6)
internal val OnSurfaceLight = Color(0xFF1C1B1F)
internal val SurfaceVariantLight = Color(0xFFE0E0E0)
internal val OnSurfaceVariantLight = Color(0xFF49454F)
internal val OutlineLight = Color(0xFF79747E)
internal val OutlineVariantLight = Color(0xFFCAC4D0)
internal val ScrimLight = Color(0xFF000000)
internal val InverseSurfaceLight = Color(0xFF313033)
internal val InverseOnSurfaceLight = Color(0xFFF4EFF4)
internal val InversePrimaryLight = Color(0xFF00FF00)

// Surface container hierarchy — light
internal val SurfaceDimLight = Color(0xFFDED8DD)
internal val SurfaceBrightLight = Color(0xFFFDF8F6)
internal val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val SurfaceContainerLowLight = Color(0xFFF7F2F7)
internal val SurfaceContainerLight = Color(0xFFF1ECF1)
internal val SurfaceContainerHighLight = Color(0xFFEBE6EB)
internal val SurfaceContainerHighestLight = Color(0xFFE5E0E5)
